sitegroup: qashot

deploy_tasks:
  development:
    before_deploy:
      - cd $AMAZEEIO_WEBROOT && composer install
      - cd $AMAZEEIO_WEBROOT && npm install -g backstopjs
    after_deploy:
      - cd $AMAZEEIO_WEBROOT && drush -y updb --cache-clear=0
      - cd $AMAZEEIO_WEBROOT && drush -y cr
  production:
    before_deploy:
      - cd $AMAZEEIO_WEBROOT && composer install
      - cd $AMAZEEIO_WEBROOT && npm install -g backstopjs
    after_deploy:
      - cd $AMAZEEIO_WEBROOT && drush -y updb --cache-clear=0
      - cd $AMAZEEIO_WEBROOT && drush -y cr

versions:
  node: 6.5.0