enabled: true
maxAge: 3600
supportsCredentials: true
allowedHeaders:
  - X-CSRF-Token
  - Content-Type
  - Authorization
allowedMethods:
  - POST
  - GET
  - OPTIONS
  - DELETE
  - PATCH
allowedOrigins:
  - '*'
exposedHeaders:
  - '*'
