sitegroup: nogroup
deploy_tasks:
  development:
    before_deploy:
      - composer install
      - npm install -g backstopjs
    after_deploy:
      - drush -y updb --cache-clear=0
      - drush -y cr
  production:
    before_deploy:
      - composer install
      - npm install -g backstopjs
    after_deploy:
      - drush -y updb --cache-clear=0
      - drush -y cr
versions:
  node: 6.3.0