version: "2"

services:

  mariadb:
    restart: always

  php:
    restart: always

  nginx:
    ports:
      - "80:80"
    restart: always
  
  pma:
    restart: always

  mailhog:
    restart: always

